[import-orig]
debian-branch = latest
upstream-branch = upstream/latest
upstream-tag = upstream/%(version)s
component = [ 'opensbi' ]
pristine-tar = True
merge-mode = auto
dch = False
interactive = False
